name: Spinnaker Webhook Tests

on:
  push: {}

jobs:
  works-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.SPINNAKER_TOKEN }}
          host: ${{ secrets.SPINNAKER_HOST }}
          name: ${{ secrets.SPINNAKER_NAME }}

  works-input-with-extra-params:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.SPINNAKER_TOKEN }}
          host: ${{ secrets.SPINNAKER_HOST }}
          name: ${{ secrets.SPINNAKER_NAME }}
          extraParams: '{"hello":"adam"}'

  works-env:
    runs-on: ubuntu-latest
    env:
      SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_TOKEN }}
      SPINNAKER_WEBHOOK_HOST: ${{ secrets.SPINNAKER_HOST }}
      SPINNAKER_WEBHOOK_NAME: ${{ secrets.SPINNAKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./

  works-env-with-extra-params:
    runs-on: ubuntu-latest
    env:
      SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_TOKEN }}
      SPINNAKER_WEBHOOK_HOST: ${{ secrets.SPINNAKER_HOST }}
      SPINNAKER_WEBHOOK_NAME: ${{ secrets.SPINNAKER_NAME }}
      SPINNAKER_WEBHOOK_EXTRA_PARAMS: '{"hello":"adam"}'
    steps:
      - uses: actions/checkout@v2
      - uses: ./

  fails-no-token:
    runs-on: ubuntu-latest
    env:
      SPINNAKER_HOST: ${{ secrets.SPINNAKER_HOST }}
      SPINNAKER_WEBHOOK_NAME: ${{ secrets.SPINNAKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          set +e
          ./spinnaker-webhook.sh
          test "1" = "$?"

  fails-no-host:
    runs-on: ubuntu-latest
    env:
      SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_TOKEN }}
      SPINNAKER_WEBHOOK_NAME: ${{ secrets.SPINNAKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          set +e
          ./spinnaker-webhook.sh
          test "1" = "$?"

  fails-no-webhook:
    runs-on: ubuntu-latest
    env:
      SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_TOKEN }}
      SPINNAKER_WEBHOOK_HOST: ${{ secrets.SPINNAKER_HOST }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          set +e
          ./spinnaker-webhook.sh
          test "1" = "$?"
